limit polling

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -31,39 +31,40 @@ jobs:
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
 
-      - name: Poll Deployment Status
-        run: |
-          RETRIES=60
-          SLEEP_DURATION=10
-          APP_ID="0513ce4c-b074-4139-bb38-a1c6a5bc97a6"
-          DIGITALOCEAN_ACCESS_TOKEN="${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
-          echo "Polling DigitalOcean App Platform deployment status..."
-          for ((i=1;i<=RETRIES;i++)); do
-            echo "Making request to DigitalOcean API..."
-            RESPONSE=$(curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" "https://api.digitalocean.com/v2/apps/$APP_ID/deployments")
-            echo "Response: $RESPONSE"
-            if echo "$RESPONSE" | jq -e '.errors' > /dev/null; then
-              echo "Error in response: $(echo $RESPONSE | jq '.errors')"
-              exit 1
-            fi
-            DEPLOYMENT_STATUS=$(echo $RESPONSE | jq -r '.deployments[0] | select(.progress.summary_steps[].status == "SUCCESS" and .progress.summary_steps[].name == "deploy").progress.summary_steps[].status')
-            echo "Attempt $i: Deployment status is $DEPLOYMENT_STATUS"
-            if [ "$DEPLOYMENT_STATUS" == "SUCCESS" ]; then
-              echo "Deployment completed successfully."
-              break
-            fi
-            if [ $i -eq $RETRIES ]; then
-              echo "Deployment did not complete after $RETRIES attempts."
-              exit 1
-            fi
-            sleep $SLEEP_DURATION
-          done
-          if [ "$DEPLOYMENT_STATUS" != "SUCCESS" ]; then
-            echo "Deployment did not succeed."
-            exit 1
-          fi
-        env:
-          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
+- name: Poll Deployment Status
+  run: |
+    RETRIES=60
+    SLEEP_DURATION=10
+    APP_ID="0513ce4c-b074-4139-bb38-a1c6a5bc97a6"
+    DIGITALOCEAN_ACCESS_TOKEN="${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
+    echo "Polling DigitalOcean App Platform deployment status..."
+    for ((i=1;i<=RETRIES;i++)); do
+      echo "Making request to DigitalOcean API..."
+      RESPONSE=$(curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" "https://api.digitalocean.com/v2/apps/$APP_ID/deployments?per_page=1")
+      echo "Response: $RESPONSE"
+      if echo "$RESPONSE" | jq -e '.errors' > /dev/null; then
+        echo "Error in response: $(echo $RESPONSE | jq '.errors')"
+        exit 1
+      fi
+      DEPLOYMENT_STATUS=$(echo $RESPONSE | jq -r '.deployments[0].progress.steps[] | select(.name == "deploy").status')
+      echo "Attempt $i: Deployment status is $DEPLOYMENT_STATUS"
+      if [ "$DEPLOYMENT_STATUS" == "SUCCESS" ]; then
+        echo "Deployment completed successfully."
+        break
+      fi
+      if [ $i -eq $RETRIES ]; then
+        echo "Deployment did not complete after $RETRIES attempts."
+        exit 1
+      fi
+      sleep $SLEEP_DURATION
+    done
+    if [ "$DEPLOYMENT_STATUS" != "SUCCESS" ]; then
+      echo "Deployment did not succeed."
+      exit 1
+    fi
+  env:
+    DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
+
 
       - name: Run Playwright Tests
         if: success()
